### ISSUE TITLE
Integration Features

### ISSUE THREAD

**Issue by giannik** [EasyOC/EasyOC#1]
Can you import content into orchard from excel files for a specific content type?

**Comment by hyzx86** [comment]
yes , you can try workflow like this:

![image](https://user-images.githubusercontent.com/15613121/150297876-c69e02da-b8aa-4939-9693-f65d33059025.png)

![image](https://user-images.githubusercontent.com/15613121/150297866-457aa65b-b766-477c-99c2-59abf6606335.png)

![image](https://user-images.githubusercontent.com/15613121/150296734-1136bdaf-cd47-4554-b95b-c5e3a44fc967.png)

![image](https://user-images.githubusercontent.com/15613121/150297602-9280fc0b-826c-459f-b03e-b768d65b31e0.png)
![image](https://user-images.githubusercontent.com/15613121/150297655-36ef1298-e616-4258-8238-1491bee0cdab.png)

**Comment by giannik** [comment]
Interesting .
Can you export the workflow recipe and attach it here ?
Just to clearly understand the steps.
Thank you.

**Comment by hyzx86** [comment]
![image](https://user-images.githubusercontent.com/15613121/150305029-6e45eb82-6b13-4247-a2e1-e4e2e560b6bc.png)
[ExportWorkflow.zip](https://github.com/EasyOC/EasyOC/files/7903670/ExportWorkflow.zip)

**Comment by hyzx86** [comment]
The file full path, if using the network path, please ensure that the current program running account has access.
![image](https://user-images.githubusercontent.com/15613121/150305343-e3f6d595-e26b-4193-83d5-739e83a4b643.png)

**Comment by hyzx86** [comment]
If an error occurs during the import process, you can view the details of the `Error ` workflow instance

**Comment by giannik** [comment]
Thank you!
Will give it a try.
