### ISSUE TITLE
Cannot run  setup recipe

### ISSUE THREAD

**Issue by giannik** [EasyOC/EasyOC#2]
I cloned project and tried to run the setup but I cannot get it to work. 

I created a local repo where I changed some settings to target net 6.0 but still get a blank screen when running.
No errors in logs. 
Can you try to run this clone as see if it shows the stup screen ?
https://github.com/giannik/EasyOC/tree/target-net.6.0

**Comment by hyzx86** [comment]
any logs?

**Comment by giannik** [comment]
no. 
eventually I copied the modules to a new host project and it worked.
Thanks
