### ISSUE TITLE
Does freesql help in doing json queries in orchards db?

### ISSUE THREAD

**Issue by giannik** [EasyOC/EasyOC#22]
Since orchards records are stored in the documents table in json format does freesql help in writing queries in json and return objects ?
Ive seen freesql has some json extensions but cant find examples on how to use them

**Comment by hyzx86** [comment]
follow 

https://github.com/EasyOC/EasyOC/blob/388f4f81c943befd8f9b82f654d6bb1fe728066f/src/Modules/EasyOC.OrchardCore.DynamicTypeIndex/Service/DynamicIndexAppService.cs#L57

and 

https://github.com/EasyOC/EasyOC/blob/388f4f81c943befd8f9b82f654d6bb1fe728066f/src/Modules/EasyOC.OrchardCore.DynamicTypeIndex/Service/DynamicIndexAppService.cs#L232

They are webapis and you can find them in the swagger documentation
Then call through spa program
