### ISSUE TITLE
mysql引擎 ， easyoc.core 的FreeSql.Provider.MySql 引用错误  

### ISSUE THREAD

**Issue by onestar1** [EasyOC/EasyOC#27]
FreeSql.Provider.MySql
要替换成

FreeSql.Provider.MySqlConnector

不然mysql引擎的时候 无法使用。

另外不能加表名前缀，不然也是
{
  "message": "Table 'xxx.superuserindex' doesn't exist",
  "statusCode": 500
}

**Comment by hyzx86** [comment]
是的，谢谢，这个已经在内部版本中更新，稍后在这里也更新下
表别名 你是在哪里用的？

**Comment by onestar1** [comment]
别表名已经解决， 是安装主题之后，使用 swagger 测试，出现问题。
![image](https://github.com/EasyOC/EasyOC/assets/10646303/5a17718d-b5ab-42ab-a684-97d671fb82df)

**Comment by onestar1** [comment]
EasyOC.RDBMS 中  CreateOrEdit.cshtml 里面的 路由地址 跟后台admin控制器的名称不对应。
或者说 是要访问 RDBMSAppService的接口。 但是 CreateOrEdit 里面的接口 跟RDBMSAppService的不对应。 结果也不一致
![image](https://github.com/EasyOC/EasyOC/assets/10646303/f2772cfd-d300-45e4-ac9e-491de20a0380)
![image](https://github.com/EasyOC/EasyOC/assets/10646303/64024f20-6fef-47cc-bd86-9a93e604401c)

**Comment by hyzx86** [comment]
`@Href()` 将会自动追加 租户前缀 可以检查 浏览器控制台

**Comment by hyzx86** [comment]
确实。。这里拼错了

**Comment by onestar1** [comment]
/api/Users/GetAll  调用这个接口 会提示 表不存在 。 是否要手动 创建 表

![image](https://github.com/EasyOC/EasyOC/assets/10646303/d48d7fed-b59b-4ad8-a9e7-5dc51f6bfc92)

{
  "message": "Table 'easysuper.userprofile_dindex' doesn't exist",
  "statusCode": 500
}

**Comment by onestar1** [comment]
> 确实。。这里拼错了

要是这样的话 调用 获取返回的参数 要用data.data 而不是 data.result了 
`
 loadConnections() {
     $.get("@Href("~/api/RDBMS/GetAllDbConnection")",{  __RequestVerificationToken: $("input[name='__RequestVerificationToken']").val()}, (data) => {
         this.allDbConnecton = data.result;
     })
 },
`

   this.allDbConnecton = data.data 

loadAllTables 也一样。 
默认的filterText   会跟connectionConfigId 一样 造成  数据表加载是空的。
`
loadAllTables(filterText) {
    if (this.model.connectionConfigId) {
        this.tableFilter.connectionConfigId = this.model.connectionConfigId;
        console.log('filterText', filterText);
        this.tableFilter.filterText = filterText;
        this.loading = true;
        $.get("@Href("~/api/RDBMS/GetAllTables")", this.tableFilter, (data, status) => {
            if (status != "success") {
                console.log(status)
                this.$message("查询失败")
            } else {
                this.allTables = data.result;
            }
            this.loading = false;
        })
    } else {
        this.allTables = []
    }
},
`
![image](https://github.com/EasyOC/EasyOC/assets/10646303/3832fcf6-01ee-4b40-9920-0b48cb3819eb)

**Comment by onestar1** [comment]
> ~~ 这里已经重构了 晚点我整理下代码 发布下

非常感谢 大佬的这个项目， 比oc本身的有很大的优化 还有实用性。 性能也非常好。   
就是前端那个项目 本地无法运行。 不清楚什么原因。  是否已经放弃那个项目https://github.com/EasyOC/EasyOC.VbenAdmin

**Comment by hyzx86** [comment]
目前这个版本 用的早期版本的 Natasha 做动态编译。所以内存会占用很高。。

**Comment by onestar1** [comment]
> 目前这个版本 用的早期版本的 Natasha 做动态编译。所以内存会占用很高。。
哦哦。   可以直接更新 natasha 版本就可以解决吗？
