### ISSUE TITLE
项目启动会报错，NatashaInitiizer .preheating() 执行错误

### ISSUE THREAD

**Issue by onestar1** [EasyOC/EasyOC#29]
这个没跟踪到是什么原因。 应该不是版本问题吧。
program-main 执行错误。
![image](https://github.com/EasyOC/EasyOC/assets/10646303/8b0fd73c-0a11-4be3-a120-13195d512359)

发生异常: CLR/NatashaException
“NatashaException”类型的异常在 EasyOC.CMS.WebHost.dll 中发生，但未在用户代码中进行处理: '应输入标识符'
   在 AssemblyCSharpBuilder.Add(String script)
   在 NatashaInitializer.Preheating(Func`3 excludeReferencesFunc)
   在 EasyOC.CMS.WebHost.Program.<>c.<Main>b__0_0() 在 e:\\2024\EasyOC\EasyOC-github\EasyOC\src\EasyOC.CMS.WebHost\Program.cs 中: 第 20 行
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   在 System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by hyzx86** [comment]
这个错误忽略就好了。。  应该不影响运行
