### ISSUE TITLE
发布任务内容的 generate from rdbms json 是不是不能用？

### ISSUE THREAD

**Issue by onestar1** [EasyOC/EasyOC#34]
![image](https://github.com/EasyOC/EasyOC/assets/10646303/7de568e5-8e71-4a72-802e-b6e6553584ca)

**Comment by hyzx86** [comment]
看起来是的。。 估计是 boostrap api 更新了，这个地方应该有个弹窗，另外注意到 api 也都要调整了

**Comment by onestar1** [comment]
表示对 boostrap api 一窍不通 ****

**Comment by hyzx86** [comment]
看了下代码。。并不是，因为我后续抛弃了mvc页面，在低代码前端重构了UI ，所以这个功能目前是需要到 amis 项目上运行的
