### ISSUE TITLE
Script Query 的使用： params 必须是 parameters

### ISSUE THREAD

**Issue by onestar1** [EasyOC/EasyOC#35]
shellDb.GetRows('Select * from Document where id=@id',params), 注意遵循不同数据库的语法规范

parameters 要用IDictionary<string, object> 格式的json
`{
    
      
        "Id": 1,
        "Name": "John Doe",
        "IsVerified": true,
        "Roles": [
            "Admin",
            "User"
        ],
        "Profile": {
            "Age": 30,
            "Country": "USA"
        }
}`

要将 params 修改为： parameters 。 后台代码已经定死了
![image](https://github.com/EasyOC/EasyOC/assets/10646303/26195127-cca8-42ad-9063-606d95a537c4)

**Comment by onestar1** [comment]
也错了。 参数不会生效。

**Comment by hyzx86** [comment]
... 谁给你说的啊 params 是变量名称 ,变量名称 随便你取什么名字
```js
var params1= {age:parameters.age}

excuteObjectQuery("Test",params1)

```

**Comment by onestar1** [comment]
我再试试看

**Comment by onestar1** [comment]
![image](https://github.com/EasyOC/EasyOC/assets/10646303/a737840e-bc6c-47dc-bd7a-9eb32c44d314)
  这个是不用管？

**Comment by hyzx86** [comment]
![image](https://github.com/EasyOC/EasyOC/assets/15613121/24e5b2f2-eb78-409a-a6d3-8de729f1504a)

**Comment by onestar1** [comment]
懂了 感谢

**Comment by onestar1** [comment]
写完之后 最后把工作流的id 关联到这个脚本也是可以的？

**Comment by hyzx86** [comment]
工作流里用 脚本任务 调用
 excuteObjectQuery(“这个Query”)

**Comment by onestar1** [comment]
ok ，run scrpitQuery  这几个是用来调试的。 
要添加脚本任务 就用所有查询里面 添加新的查询 。 对应parameters  这个就相当于 Schema ？ 其他的内容是没变咯。

**Comment by onestar1** [comment]
我去看看文档
